In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a=pd.read_csv("/content/Student_Productivity_Dataset.csv")

In [ ]:
a.columns

Index(['Student_ID', 'Age', 'Gender', 'Study_Hours_Per_Day',
       'Sleep_Hours_Per_Night', 'Screen_Time_Hours', 'Social_Media_Hours',
       'Attendance_Percentage', 'Assignments_Completed',
       'Class_Participation_Score', 'Physical_Activity_Hours_Per_Week',
       'Stress_Level', 'Motivation_Level', 'Internet_Quality', 'Part_Time_Job',
       'Extracurricular_Involvement', 'AI_Tool_Usage_Hours_Per_Week',
       'Previous_Semester_GPA', 'Productivity_Score', 'Performance_Category'],
      dtype='object')

In [ ]:
a.columns.str.strip()

Index(['Student_ID', 'Age', 'Gender', 'Study_Hours_Per_Day',
       'Sleep_Hours_Per_Night', 'Screen_Time_Hours', 'Social_Media_Hours',
       'Attendance_Percentage', 'Assignments_Completed',
       'Class_Participation_Score', 'Physical_Activity_Hours_Per_Week',
       'Stress_Level', 'Motivation_Level', 'Internet_Quality', 'Part_Time_Job',
       'Extracurricular_Involvement', 'AI_Tool_Usage_Hours_Per_Week',
       'Previous_Semester_GPA', 'Productivity_Score', 'Performance_Category'],
      dtype='object')

In [ ]:
a.isnull().sum()

Student_ID                            0
Age                                 155
Gender                              119
Study_Hours_Per_Day                 165
Sleep_Hours_Per_Night               106
Screen_Time_Hours                   132
Social_Media_Hours                   80
Attendance_Percentage               122
Assignments_Completed               118
Class_Participation_Score           185
Physical_Activity_Hours_Per_Week    137
Stress_Level                        154
Motivation_Level                    175
Internet_Quality                    149
Part_Time_Job                       126
Extracurricular_Involvement         178
AI_Tool_Usage_Hours_Per_Week        140
Previous_Semester_GPA               161
Productivity_Score                    0
Performance_Category                  0
dtype: int64

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Student_ID                        10000 non-null  int64
 1   Age                               9845 non-null   float64
 2   Gender                            9881 non-null   object
 3   Study_Hours_Per_Day               9835 non-null   float64
 4   Sleep_Hours_Per_Night             9894 non-null   float64
 5   Screen_Time_Hours                 9868 non-null   float64
 6   Social_Media_Hours                9920 non-null   float64
 7   Attendance_Percentage             9878 non-null   float64
 8   Assignments_Completed             9882 non-null   float64
 9   Class_Participation_Score         9815 non-null   float64
 10  Physical_Activity_Hours_Per_Week  9863 non-null   float64
 11  Stress_Level                      9846 non-null   float64
 12  Motivation_Level                  9825 non-null   float64
 13  Internet_Quality                  9851 non-null   object
 14  Part_Time_Job                     9874 non-null   object
 15  Extracurricular_Involvement       9822 non-null   float64
 16  AI_Tool_Usage_Hours_Per_Week      9860 non-null   float64
 17  Previous_Semester_GPA             9839 non-null   float64
 18  Productivity_Score                10000 non-null  float64
 19  Performance_Category              10000 non-null  object
dtypes: float64(15), int64(1), object(4)
memory usage: 1.5+ MB

In [ ]:
a

,Student_ID,Age,Gender,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Internet_Quality,Part_Time_Job,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,1,19.0,Male,2.6,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,Poor,No,4.9,16.4,5.88,51.16,Medium
1,2,25.0,Male,5.4,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,Good,No,3.9,2.1,6.62,74.10,High
2,3,22.0,Male,6.8,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,Average,No,4.9,3.6,7.11,34.63,Low
3,4,21.0,Female,1.7,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,Poor,No,2.8,8.5,6.85,53.20,Medium
4,5,17.0,Male,7.6,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,Average,No,4.5,5.3,5.86,57.40,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.0,Female,4.2,5.5,5.2,1.6,95.5,100.0,6.6,5.0,7.7,8.5,Average,No,9.0,6.3,6.51,80.59,High
9996,9997,24.0,Male,7.1,6.7,4.0,3.2,64.3,74.5,4.0,0.5,6.8,9.4,Good,Yes,7.0,7.1,6.97,62.95,Medium
9997,9998,24.0,Male,6.4,4.4,6.7,3.3,74.1,100.0,10.0,4.5,5.4,1.0,Average,No,0.0,8.2,1.80,43.79,Low
9998,9999,19.0,Male,8.1,6.8,3.5,4.1,59.5,85.9,7.2,4.6,5.0,5.8,Poor,Yes,4.1,3.5,5.24,49.48,Medium
9999,10000,18.0,Male,4.6,7.2,6.8,3.1,66.0,32.1,7.4,2.3,6.4,9.2,Good,No,7.2,4.0,5.54,62.81,Medium

In [ ]:
a=a.drop("Student_ID",axis=1)

In [ ]:
a.dropna(inplace=True)

In [ ]:
a

,Age,Gender,Study_Hours_Per_Day,Sleep_Hours_Per_Night,Screen_Time_Hours,Social_Media_Hours,Attendance_Percentage,Assignments_Completed,Class_Participation_Score,Physical_Activity_Hours_Per_Week,Stress_Level,Motivation_Level,Internet_Quality,Part_Time_Job,Extracurricular_Involvement,AI_Tool_Usage_Hours_Per_Week,Previous_Semester_GPA,Productivity_Score,Performance_Category
0,19.0,Male,2.6,5.9,7.4,2.8,86.3,75.1,3.8,2.8,1.4,6.3,Poor,No,4.9,16.4,5.88,51.16,Medium
1,25.0,Male,5.4,6.4,6.4,4.1,93.3,99.6,7.9,0.5,8.3,8.2,Good,No,3.9,2.1,6.62,74.10,High
2,22.0,Male,6.8,5.5,7.4,4.3,66.3,75.6,4.0,1.7,9.3,4.1,Average,No,4.9,3.6,7.11,34.63,Low
3,21.0,Female,1.7,8.0,6.2,2.4,62.8,51.9,3.0,2.5,2.5,10.0,Poor,No,2.8,8.5,6.85,53.20,Medium
4,17.0,Male,7.6,6.2,4.3,3.7,87.9,37.0,8.8,3.3,6.1,8.0,Average,No,4.5,5.3,5.86,57.40,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23.0,Female,4.2,5.5,5.2,1.6,95.5,100.0,6.6,5.0,7.7,8.5,Average,No,9.0,6.3,6.51,80.59,High
9996,24.0,Male,7.1,6.7,4.0,3.2,64.3,74.5,4.0,0.5,6.8,9.4,Good,Yes,7.0,7.1,6.97,62.95,Medium
9997,24.0,Male,6.4,4.4,6.7,3.3,74.1,100.0,10.0,4.5,5.4,1.0,Average,No,0.0,8.2,1.80,43.79,Low
9998,19.0,Male,8.1,6.8,3.5,4.1,59.5,85.9,7.2,4.6,5.0,5.8,Poor,Yes,4.1,3.5,5.24,49.48,Medium
9999,18.0,Male,4.6,7.2,6.8,3.1,66.0,32.1,7.4,2.3,6.4,9.2,Good,No,7.2,4.0,5.54,62.81,Medium

In [ ]:
a["Study_Hours_Per_Day"].value_counts()

Study_Hours_Per_Day
4.3     191
4.7     174
4.5     172
5.2     170
4.2     165
       ...
10.4      1
10.0      1
9.6       1
10.5      1
10.6      1
Name: count, Length: 109, dtype: int64

In [ ]:
x=a[["Study_Hours_Per_Day"]]
y=a[["Performance_Category"]]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_test,x_train,y_test,y_train=train_test_split(x,y,train_size=0.7,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
aa=LogisticRegression()

In [ ]:
aa.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [ ]:
y_prediction=aa.predict(x_test)
y_prediction

array(['Medium', 'Medium', 'Medium', ..., 'Medium', 'Medium', 'Medium'],
      dtype=object)

In [ ]:
y_test

     Performance_Category
3982               Medium
3318               Medium
3251               Medium
7749               Medium
767                   Low
...                   ...
6624                  Low
6825                  Low
1083                 High
9654               Medium
9228                 High

[5510 rows x 1 columns]

In [ ]:
aa.predict(np.array([[3]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Medium'], dtype=object)

In [ ]:
from sklearn.metrics import r2_score